access_token: <GitHub Personal Access Token>
max_concurrent: 3
start_point:
  path: avelino/awesome-go

## Output final JSON data.
## default: stdout
output:
  path: ./awg.json

log:
  ## Main log.
  main:
    ## default: stderr
    path:
      - /tmp/awesome-github.log

  ## HTTP log.
  http:
    ## default: stderr
    path:
      - /tmp/awesome-github.log
