## Your GitHub personal access token, used to request GitHub API.
## Prefer ${GITHUB_ACCESS_TOKEN} env var.
access_token: <GitHub Personal Access Token>
## Max concurrent requests to GitHub API.
max_concurrent: 3
## Crawler start point.
start_point:
  ## Awesome-XXX repostiory path, can be found in URL.
  path: avelino/awesome-go

network:
  ## Retry request if network error occurs.
  retry_time: 2
  retry_interval: 1s

## Output final JSON data.
output:
  ## default: stdout
  path: ./awg.json

## Command line interface
cli:
  disable_progress_bar: false

## GitHub server settings.
github:
  # html_host: ""
  # api_host: ""

log:
  ## Main log.
  main:
    ## default: stderr
    path:
      - /tmp/awesome-github.log

  ## HTTP log.
  http:
    ## default: stderr
    path:
      - /tmp/awesome-github.log
