before:
  hooks:
    - go mod download
builds:
  - goos:
    - linux
    - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "latest"
changelog:
  sort: asc
  filters:
    exclude:
    - '^style'
    - '^refactor'
    - '^test'
    - '^docs'
    - '^chore'
