name: Unit-Tests
on: [push]
jobs:
  test:
    name: Test on ${{ matrix.os }} go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        go_version: [1.14]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    - name: Test
      run: go test ./...
